[theme]
primaryColor = "#FF8C42"  # Jingga muda
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
